### ISSUE TITLE
Job fails because of time out

### ISSUE THREAD

**Issue by dafnevk** [xenon-middleware/xenon-flow#29]
When I run my cwl workflow, the job fails with the following error:
```
2018-Jul-03 10:55:16.620 ERROR - Exception during execution
nl.esciencecenter.xenon.adaptors.schedulers.JobCanceledException: local adaptor: Process timed out.
	at nl.esciencecenter.xenon.adaptors.schedulers.JobExecutor.run(JobExecutor.java:371)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-Jul-03 10:55:16.627 ERROR - Error during execution of Analyze Fiqh latest version(56886295-a16b-46a8-8e7f-376d90ce1fcf)
nl.esciencecenter.xenon.adaptors.schedulers.JobCanceledException: local adaptor: Process timed out.
	at nl.esciencecenter.xenon.adaptors.schedulers.JobExecutor.run(JobExecutor.java:371)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-Jul-03 10:55:16.653 INFO - Job 56886295-a16b-46a8-8e7f-376d90ce1fcf now has state: Permanent_Failure
```

I don't see any errors or other worrying output in the stderr of the job.
Is there a default time out in Xenon, and is there a way to configure it in xenon-flow to prevent this from happening? Or is there a different cause of this exception?

**Comment by jmaassen** [comment]
This exception is the result of the process running longer than was specified in the JobDescription. The default is 15 minutes at the moment. Setting the maxRuntime to 0 will give you "infinite time".  

Is this something you can specify in your workflow, or does xenon-flow simply use the default?

**Comment by bpmweel** [comment]
It seems I just use the default.

The cwl specification allows for hinting: https://www.commonwl.org/v1.0/CommandLineTool.html#Execution, so I think this may be a good place to implement this.

Then the default could go to 0 and the hint can change that.

@jmaassen are there systems / adaptors that require a non 0 maxRuntime?

**Comment by sverhoeven** [comment]
Yes, system admins can configure the batch scheduler to require a set max runtime.

**Comment by LourensVeen** [comment]
IMHO it should be a [ResourceRequirement](https://www.commonwl.org/v1.0/CommandLineTool.html#ResourceRequirement), see also https://github.com/common-workflow-language/common-workflow-language/issues/590, but it's going to be a [TimeLimit](https://www.commonwl.org/v1.1.0-dev1/CommandLineTool.html#TimeLimit) in CWL 1.1 apparently.

**Comment by jmaassen** [comment]
@bpmweel I think I have never used a cluster that did not require a max runtime of a job to be specified, or alternatively, that would default to a relatively short value (like 15 minutes or 1 hour) if you did not specify anything. Some sites also have an upper limit. At Cartesius it is 5 days for example, but I've also used supers that had a 24 hour limit.

The default of xenon is arbitrarily chosen to have the same value as the DAS ;-) We can set it so something else, but setting it to 0 will not always work because some clusters require you to set a value. 

In the end the user will have to think about what run time would be acceptable. This is not something we can determine automatically.

**Comment by bpmweel** [comment]
As a first step I have implemented a new config option for ComputeResource that allows you to override the default Xenon maxRunTime.

it is **maxTime** and expects an integer representing the **maximum time** (and thus the time reserved on the compute resource) in **minutes**

```
ComputeResources:
     local:
        maxTime: 20
        cwlCommand: /some/path/to/a/cwl/runner
        scheduler:
            adaptor: local
            location: /some/path/where/to/run/locally
```
