### ISSUE TITLE
Implement standard cwl runner

### ISSUE THREAD

**Issue by nielsdrost** [xenon-middleware/xenon-flow#3]
There is a standard description for a cwlrunner now:

https://github.com/common-workflow-language/common-workflow-language/issues/278

Ofcourse specified as a cwl script ;-)

~The Xenon runner~ Xenon Flow should implement this.

**Comment by bpmweel** [comment]
The plan is to create a command line tool that uses the rest api of Xenon Flow.

**Comment by mr-c** [comment]
Hello @bpmweel, any progress on a `xenon-cwl-runner`? Even just for testing a completely local install it would be nice to have a sense of the progress of this implementation.

**Comment by mr-c** [comment]
Closing as per https://github.com/xenon-middleware/xenon-flow/blob/master/xenon-flow-runner.py ; thanks!
